name: lumina
description: Lumina tribute capsule platform
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  flutter_riverpod: ^2.4.0
  go_router: ^13.2.0
  http: ^1.1.0
  universal_html: ^2.2.4
  video_player: ^2.8.2
  just_audio: ^0.9.36
  url_launcher: ^6.2.4
  flutter_dotenv: ^5.1.0
  uni_links: ^0.5.1
  file_picker: ^6.1.1
  image: ^4.1.3
  pdf: ^3.10.7
  path_provider: ^2.1.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true  
  assets:
    - assets/logo.png 
    - assets/Folleto ES.png
    - assets/Leaflet EN.png
    - assets/velatorio.png
    - .env